# Generated by Django 3.1.5 on 2021-03-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availble',
            new_name='is_available',
        ),
    ]
