# Generated by Django 3.1.5 on 2021-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210323_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
