# Generated by Django 3.1.5 on 2021-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210323_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
