# Generated by Django 3.1.5 on 2021-03-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
